version: "3.8"

services:
  db:
    image: postgres
    container_name: bs_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: backend_stuff
      POSTGRES_PASSWORD: blork_erlang
      POSTGRES_DB: real_deal_api_dev
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
